:description: Create, store, and manipulate vector embeddings in a Neo4j database.
:table-caption!:
:test-setup-dump: https://github.com/neo4j-graph-examples/recommendations/raw/main/data/recommendations-5.26-block.dump


= Create and store embeddings

Neo4j's link:{neo4j-docs-base-uri}/cypher-manual/current/indexes/semantic-indexes/vector-indexes[vector indexes] and link:{neo4j-docs-base-uri}/cypher-manual/current/functions/vector[vector functions] allow you to calculate the similarity between node and relationship properties in a graph.
A prerequisite for using these features is that vector embeddings have been set as properties of these entities.
This page shows how these embeddings can be created and stored as properties on nodes and relationships in a Neo4j database using the GenAI plugin.

[TIP]
For a hands-on guide on how to use the GenAI plugin on a Neo4j database, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/[Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].


[[single-embedding]]
== Generate and store a single embedding

Use the `ai.text.embed()` function to generate a vector embedding for a single value.

.Signature for `ai.text.embed()`
[role=label--function label--new-2025.11]
[cols="1,1,1,3"]
|===
|    *Syntax*        3+| `ai.text.embed(resource, provider, configuration = {}) :: VECTOR`
|    *Description*   3+| Encode a resource as a vector using the named provider.

.4+| *Inputs* | *Name* | *Type* | *Description*
   | `resource`
   | `STRING`
   | The string to transform into an embedding.

   | `provider`
   | `STRING`
   | Case-insensitive identifier of the AI provider to use. See xref:providers[] for supported options.

   |`configuration`
   | `MAP`
   | Provider-specific options.
See xref:providers[] for details of each supported provider.
Note that because this argument may contain sensitive data, it is obfuscated in the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/[query.log].
However, if the function call is misspelled or the query is otherwise malformed, it will be logged without obfuscation.

2+| *Returns* | `VECTOR` | The generated vector embedding for the resource.
|===

[NOTE]
This function sends one API request every time it is called, which may result in a lot of overhead in terms of both network traffic and latency.
If you want to generate many embeddings at once, use xref:multiple-embeddings[] or xref:file-embeddings.adoc[].
If you want to read text from a file and embed it, see xref:file-embeddings.adoc[].

The examples below use the recommendations dataset described in xref:index.adoc#setup[Environment setup].
Choose the tab that matches the setup you selected there.

[.tabbed-example]
====
[.include-with-Enterprise-Edition-or-Aura]
======
`ai.text.embed()` returns a link:https://neo4j.com/docs/cypher-manual/25/values-and-types/vector/[`VECTOR`].
Storing `VECTOR` values on self-managed instances requires Enterprise Edition and link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/store-formats/#store-format-overview[block format].

.Create a `VECTOR` embedding property for the Godfather
[source,cypher]
----
MATCH (m:Movie {title:'Godfather, The'})
WHERE m.plot IS NOT NULL AND m.title IS NOT NULL
WITH m, m.title + ' ' + m.plot AS titleAndPlot // <1>
WITH m, ai.text.embed(titleAndPlot, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) AS vector // <2>
SET m.embedding = vector // <3>
RETURN m.embedding AS embedding
----

<1> Concatenate the `title` and `plot` of the `Movie` into a single `STRING`.
<2> Create an embedding from `titleAndPlot`.
<3> Store the `propertyVector` into an `embedding` property (type `VECTOR`) on `The Godfather` node.

.Result (output capped after 4 entries)
[source]
----
+----------------------------------------------------------------------------------------------------+
| embedding                                                                                          |
+----------------------------------------------------------------------------------------------------+
| [0.005239539314061403, -0.039358530193567276, -0.0005175105179660022, -0.038706034421920776, ... ] |
+----------------------------------------------------------------------------------------------------+
----

======


[.include-with-Community-Edition]
======
`ai.text.embed()` returns a link:https://neo4j.com/docs/cypher-manual/25/values-and-types/vector/[`VECTOR`], which can be converted into a list with link:https://neo4j.com/docs/cypher-manual/25/functions/list/#functions-tofloatlist[`toFloatList()`].
Use this compatibility workflow on Community Edition or on databases that use aligned format.

.Create a `LIST<FLOAT>` embedding property for the Godfather
[source,cypher]
----
MATCH (m:Movie {title:'Godfather, The'})
WHERE m.plot IS NOT NULL AND m.title IS NOT NULL
WITH m, m.title + ' ' + m.plot AS titleAndPlot // <1>
WITH m, ai.text.embed(titleAndPlot, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) AS vector // <2>
CALL db.create.setNodeVectorProperty(m, 'embedding', toFloatList(vector)) // <3>
RETURN m.embedding AS embedding
----

<1> Concatenate the `title` and `plot` of the `Movie` into a single `STRING`.
<2> Create an embedding from `titleAndPlot`.
<3> Store the `propertyVector` into an `embedding` property (type `LIST<FLOAT>`) on `The Godfather` node.
The procedures link:https://neo4j.com/docs/operations-manual/current/procedures/#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty`] and link:https://neo4j.com/docs/operations-manual/current/procedures/#procedure_db_create_setRelationshipVectorProperty[`db.create.setRelationshipVectorProperty`] store the list with a more space-efficient representation.

.Result (output capped after 4 entries)
[source]
----
+----------------------------------------------------------------------------------------------------+
| embedding                                                                                          |
+----------------------------------------------------------------------------------------------------+
| [0.005239539314061403, -0.039358530193567276, -0.0005175105179660022, -0.038706034421920776, ... ] |
+----------------------------------------------------------------------------------------------------+
----

======
====


[[multiple-embeddings]]
== Generate and store a batch of embeddings

Use the `ai.text.embedBatch` procedure to generate many vector embeddings with a single API request.
This procedure takes a list of resources as an input, and returns the same number of result rows.

.Signature for `ai.text.embedBatch()`
[role=label--procedure label--new-2025.11]
[cols="1,1,1,3"]
|===
|    *Syntax*        3+| `ai.text.embedBatch(resources, provider, configuration = {}) :: (index, resource, vector)`
|    *Description*   3+| Encode a given batch of resources as vectors using the named provider.

.4+| *Inputs* | *Name* | *Type* | *Description*
   | `resources`
   | `LIST<STRING>`
   | The strings to transform into an embedding.

   | `provider`
   | `STRING`
   | Case-insensitive identifier of the AI provider to use. See xref:providers[] for supported options.

   |`configuration`
   | `MAP`
   | Provider-specific options.
See xref:providers[] for details of each supported provider.
Note that because this argument may contain sensitive data, it is obfuscated in the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/[query.log].
However, if the function call is misspelled or the query is otherwise malformed, it will be logged without obfuscation.

.4+| *Returns* | *Name* | *Type* | *Description*
   | `index`
   | `INTEGER`
   | The index of the corresponding element in the input list, to correlate results back to inputs.

   | `resource`
   | `STRING`
   | The given input resource.

   |`vector`
   | `VECTOR`
   | The generated vector embedding for this resource.
|===

[IMPORTANT]
====
This procedure attempts to generate embeddings for all supplied resources in a single API request.
Providing too many resources may cause the AI provider to time out or to reject the request.

For OpenAI, Azure OpenAI, and Vertex AI, the `maxBatchSize` configuration parameter can be used to limit the amount of data sent per each API request to the provider.
If a resource is larger than the specified `maxBatchSize`, it must be chunked manually before passing it to the procedure.
====

[.tabbed-example]
====
[.include-with-Enterprise-Edition-or-Aura]
======
`ai.text.embedBatch()` returns a `VECTOR` for each input resource.
Storing `VECTOR` values on an on-prem instance requires Enterprise Edition and link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/store-formats/#store-format-overview[block format].

.Create embeddings from a limited number of properties and store them as `VECTOR` properties
[source,cypher]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL) LIMIT 20
WITH collect(m) AS moviesList // <1>
WITH moviesList, [movie IN moviesList | movie.title + ': ' + movie.plot] AS batch // <2>
CALL ai.text.embedBatch(batch, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) YIELD index, vector
WITH moviesList, index, vector
MATCH (toUpdate:Movie {title: moviesList[index]['title']})
SET toUpdate.embedding = vector  // <3>
----

<1> link:https://neo4j.com/docs/cypher-manual/25/functions/aggregating/#functions-collect[Collect] all  20 `Movie` nodes into a `LIST<NODE>`.
<2> A link:https://neo4j.com/docs/cypher-manual/25/expressions/list-expressions/#list-comprehension[list comprehension] (`[]`) extracts the `title` and `plot` properties of the movies in `moviesList` into a new `LIST<STRING>`.
<3> `SET` is run for each `vector` returned by `ai.text.embedBatch()`, and stores that vector as a property named `embedding` on the corresponding node.

.Create embeddings from a large number properties and store them as `VECTOR` properties
[source, cypher]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL) LIMIT 500
WITH collect(m) AS moviesList, // <1>
     count(*) AS total,
     100 AS batchSize // <2>
UNWIND range(0, total-1, batchSize) AS batchStart // <3>
CALL (moviesList, batchStart, batchSize) { // <4>
    WITH [movie IN moviesList[batchStart .. batchStart + batchSize] | movie.title + ': ' + movie.plot] AS batch // <5>
    CALL ai.text.embedBatch(batch, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) YIELD index, vector
    MATCH (toUpdate:Movie {title: moviesList[batchStart + index]['title']})
    SET toUpdate.embedding = vector // <6>
} IN CONCURRENT TRANSACTIONS OF 1 ROW // <7>
----

<1> link:https://neo4j.com/docs/cypher-manual/25/functions/aggregating/#functions-collect[Collect] all returned `Movie` nodes into a `LIST<NODE>`.
<2> `batchSize` defines the number of nodes in `moviesList` to be processed at once.
Because vector embeddings can be very large, a larger batch size may require significantly more memory on the Neo4j server.
Too large a batch size may also exceed the provider's threshold.
<3> Process `Movie` nodes in increments of `batchSize`.
The end range `total-1` is due to `range` being inclusive on both ends.
<4> A link:https://neo4j.com/docs/cypher-manual/25/subqueries/subqueries-in-transactions/[`CALL` subquery] executes a separate transaction for each batch.
Note that this `CALL` subquery uses a link:https://neo4j.com/docs/cypher-manual/25/subqueries/call-subquery/#variable-scope-clause[variable scope clause].
<5> `batch` is a list of strings, each being the concatenation of `title` and `plot` of one movie.
<6> The procedure sets `vector` as value for the property named `embedding` for the node at position `batchStart + index` in the `moviesList`.
<7> Set to `1` the amount of batches to be processed at once.
For more information on concurrency in transactions, see link:https://neo4j.com/docs/cypher-manual/25/subqueries/subqueries-in-transactions/#concurrent-transactions[`CALL` subqueries -> Concurrent transactions].

[NOTE]
This example may not scale to larger datasets, as `collect(m)` requires the whole result set to be loaded in memory.
For an alternative method more suitable to processing large amounts of data, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/[Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].

======


[.include-with-Community-Edition]
======
`ai.text.embedBatch()` returns a `VECTOR` for each input resource, which can be converted into a list with link:https://neo4j.com/docs/cypher-manual/25/functions/list/#functions-tofloatlist[`toFloatList()`].
These compatibility workflows store embeddings as `LIST<FLOAT>` properties.
Use them on Community Edition, or whenever you prefer list-based storage over native `VECTOR` properties.

.Create embeddings from a limited number of properties and store them as `LIST<FLOAT>` properties
[source, cypher]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL) LIMIT 20
WITH collect(m) AS moviesList // <1>
WITH moviesList, [movie IN moviesList | movie.title + ': ' + movie.plot] AS batch // <2>
CALL ai.text.embedBatch(batch, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) YIELD index, vector
WITH moviesList, index, vector
CALL db.create.setNodeVectorProperty(moviesList[index], 'embedding', toFloatList(vector)) // <3>
----

<1> link:https://neo4j.com/docs/cypher-manual/25/functions/aggregating/#functions-collect[Collect] all  20 `Movie` nodes into a `LIST<NODE>`.
<2> A link:https://neo4j.com/docs/cypher-manual/25/expressions/list-expressions/#list-comprehension[list comprehension] (`[]`) extracts the `title` and `plot` properties of the movies in `moviesList` into a new `LIST<STRING>`.
<3> Each vector is converted into a list of floats and stored as a property named `embedding` (type `LIST<FLOAT>`) on the corresponding node.
The procedures link:https://neo4j.com/docs/operations-manual/current/procedures/#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty`] and link:https://neo4j.com/docs/operations-manual/current/procedures/#procedure_db_create_setRelationshipVectorProperty[`db.create.setRelationshipVectorProperty`] store the list with a more space-efficient representation.

.Create embeddings from a large number properties and store them as `LIST<FLOAT>` values
[source, cypher]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL) LIMIT 500
WITH collect(m) AS moviesList, // <1>
     count(*) AS total,
     100 AS batchSize // <2>
UNWIND range(0, total-1, batchSize) AS batchStart // <3>
CALL (moviesList, batchStart, batchSize) { // <4>
    WITH [movie IN moviesList[batchStart .. batchStart + batchSize] | movie.title + ': ' + movie.plot] AS batch // <5>
    CALL ai.text.embedBatch(batch, 'OpenAI', { token: $openaiToken, model: 'text-embedding-3-small' }) YIELD index, vector
    CALL db.create.setNodeVectorProperty(moviesList[batchStart + index], 'embedding', toFloatList(vector)) // <6>
} IN CONCURRENT TRANSACTIONS OF 1 ROW // <7>
----

<1> link:https://neo4j.com/docs/cypher-manual/25/functions/aggregating/#functions-collect[Collect] all returned `Movie` nodes into a `LIST<NODE>`.
<2> `batchSize` defines the number of nodes in `moviesList` to be processed at once.
Because vector embeddings can be very large, a larger batch size may require significantly more memory on the Neo4j server.
Too large a batch size may also exceed the provider's threshold.
<3> Process `Movie` nodes in increments of `batchSize`.
The end range `total-1` is due to `range` being inclusive on both ends.
<4> A link:https://neo4j.com/docs/cypher-manual/25/subqueries/subqueries-in-transactions/[`CALL` subquery] executes a separate transaction for each batch.
Note that this `CALL` subquery uses a link:https://neo4j.com/docs/cypher-manual/25/subqueries/call-subquery/#variable-scope-clause[variable scope clause].
<5> `batch` is a list of strings, each being the concatenation of `title` and `plot` of one movie.
<6> The procedure sets `vector` as value for the property named `embedding` for the node at position `batchStart + index` in the `moviesList`.
<7> Set to `1` the amount of batches to be processed at once.
For more information on concurrency in transactions, see link:https://neo4j.com/docs/cypher-manual/25/subqueries/subqueries-in-transactions/#concurrent-transactions[`CALL` subqueries -> Concurrent transactions].

[NOTE]
This example may not scale to larger datasets, as `collect(m)` requires the whole result set to be loaded in memory.
For an alternative method more suitable to processing large amounts of data, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/[GenAI documentation - Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].

======
====


[[providers]]
== Providers

You can create vector embeddings via the following providers:

- OpenAI (`openai`)
- Azure OpenAI (`azure-openai`)
- Google Vertex AI (`vertexai`)
- Amazon Bedrock Titan Models (`bedrock-titan`)

The query `CALL ai.text.embed.providers()` (see xref:reference/functions-procedures.adoc#ai-text-embed-providers[reference]) shows the list of supported providers in the installed version of the plugin.


[[providers-openai]]
=== OpenAI

.OpenAI parameters
[opts=header, cols="1,1,1,3"]
|===
| *Name*          | *Type*   | *Default* | *Description*
| `model`         | `STRING` | -         | Model ID (see https://platform.openai.com/docs/models[OpenAI -> Models]).
| `token`         | `STRING` | -         | OpenAI API key (see https://platform.openai.com/api-keys[OpenAI -> API Keys]).
| `maxBatchSize`  | `INTEGER`| `8192`    | The maximum amount of data (measured in tokens) sent at a time. label:new[Introduced in 2026.04]
| `vendorOptions` | `MAP`    | `{}`      | Optional vendor options that will be passed on as-is in the request to Open AI (see https://platform.openai.com/docs/api-reference/embeddings/create[OpenAI -> Create embeddings]).
|===

.Example -- Embed the string `Hello World!`
[source, cypher, test-result-skip]
----
WITH
  {
    token: $openaiToken,
    model: 'text-embedding-3-small',
    vendorOptions: {
      dimensions: 1024
    }
  } AS conf
RETURN ai.text.embed('Hello World!', 'openai', conf) AS result
----

[NOTE]
You can change OpenAI's base URL (default: https://api.openai.com) via the `genai.openai.baseurl` setting.
The change applies to all `ai.text.*` calls that use OpenAI, including `ai.text.embed`, `ai.text.embedBatch` and `ai.text.completion`.
See xref:reference/config.adoc#config-genai.openai.baseurl[Configuration Options -> genai.openai.baseurl].


[[providers-azure-openai]]
=== Azure OpenAI

.Azure OpenAI parameters
[opts=header, cols="1,1,1,3"]
|===
| *Name*          | *Type*   | *Default* | *Description*
| `model`         | `STRING` | -         | Model id (see https://learn.microsoft.com/en-us/azure/ai-foundry/openai/overview[Azure -> Azure OpenAI in Foundry Models]).
| `resource`      | `STRING` | -         | Azure resource name.
| `token`         | `STRING` | -         | Azure OAuth2 bearer token.
| `maxBatchSize`  | `INTEGER`| `8192`    | The maximum amount of data (measured in tokens) sent at a time. label:new[Introduced in 2026.04]
| `vendorOptions` | `MAP`    | `{}`      | Optional vendor options that will be passed on as-is in the request to Azure.
|===

.Example -- Embed the string `Hello World!`
[source, cypher]
----
WITH
  {
    token: $azureToken,
    resource: 'my-azure-openai-resource',
    model: 'text-embedding-3-small',
    vendorOptions: {
      dimensions: 1024
    }
  } AS conf
RETURN ai.text.embed('Hello World!', 'azure-openai', conf) AS result
----

[NOTE]
Since 2026.04, you can change Azure OpenAI's base URL via the `genai.azure.openai.baseurl` setting.
The change applies to all `ai.text.*` calls that use Azure OpenAI.
See xref:reference/config.adoc#config-genai.azure.openai.baseurl[Configuration Options -> genai.azure.openai.baseurl].


[[providers-google-vertexai]]
=== Google VertexAI

.Google VertexAI parameters
[opts=header, cols="1,1,1,3"]
|===
| *Name*          | *Type*   | *Default*  | *Description*
| `model`         | `STRING` | -          | Model resource name (see https://console.cloud.google.com/vertex-ai/model-garden[Vertex AI -> Model Garden]).
| `project`       | `STRING` | -          | Google Cloud project ID.
| `region`        | `STRING` | -          | Google cloud region (see https://cloud.google.com/vertex-ai/docs/general/locations[Vertex AI -> Locations]).
| `publisher`     | `STRING` | `'google'` | Model publisher.
| `apiKey`        | `STRING` | -          | Vertex AI API key.
| `token`         | `STRING` | -          | Vertex AI API access token.
| `maxBatchSize`  | `INTEGER`| -          | The maximum amount of data (measured in tokens) sent at a time. label:new[Introduced in 2026.04]
| `vendorOptions` | `MAP`    | `{}`       | Optional vendor options that will be passed on as-is in the request to Vertex (see https://cloud.google.com/vertex-ai/generative-ai/docs/reference/rest/v1/projects.locations.publishers.models/predict[Vertex AI -> Method: models.predict]).
|===

[NOTE]
Exactly one of `apiKey` or `token` must be provided.

.Example -- Embed the string `Hello World!`
[source, cypher]
----
WITH
  {
    token: $vertexaiApiAccessKey,
    model: 'gemini-embedding-001',
    publisher: 'google',
    project: 'my-google-cloud-project',
    region: 'asia-northeast1',
    vendorOptions: {
      outputDimensionality: 1024
    }
  } AS conf
RETURN ai.text.embed('Hello World!', 'vertexai', conf) AS result
----


[[providers-amazon-bedrock-titan]]
=== Amazon Bedrock Titan Models

This provider supports all models that use the same request parameters and response fields as the https://docs.aws.amazon.com/bedrock/latest/userguide/titan-embedding-models.html[Titan text models].

.Amazon Bedrock Titan Configuration
[opts=header, cols="1,1,1,3"]
|===
| *Name*            | *Type*   | *Default* | *Description*
| `model`           | `STRING` | -         | Model ID or its ARN.
| `region`          | `STRING` | -         | Amazon region (see https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html[Amazon Bedrock -> Model Support]).
| `accessKeyId`     | `STRING` | -         | Amazon access key ID.
| `secretAccessKey` | `STRING` | -         | Amazon secret access key.
| `vendorOptions`   | `MAP`    | `{}`      | Optional vendor options that will be passed on as-is in the request to Bedrock (see https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html[Amazon Bedrock -> Inference request parameters and response fields]).
|===

.Example -- Embed the string `Hello World!`
[source, cypher]
----
WITH
  {
    accessKeyId: $awsAccessKeyId,
    secretAccessKey: $secretAccessKey,
    model: 'amazon.titan-embed-text-v1',
    region: 'eu-west-2',
    vendorOptions: {
      dimensions: 1024
    }
  } AS conf
RETURN ai.text.embed('Hello World!', 'bedrock-titan', conf) AS result
----


[role=label--deprecated-2025.11]
[[legacy-providers]]
== (Legacy) Providers

The following provider configurations are for the `genai.vector.encode` function and the `genai.vector.encodeBatch` procedure.
Both callables have been deprecated in 2025.11 and superseded by xref:single-embedding[`ai.text.embed`] and xref:multiple-embeddings[`ai.text.embedBatch`].
For more information on the old callables, see link:https://neo4j.com/docs/genai/plugin/5/embeddings/[documentation for the previous version].


[[legacy-provider-openai]]
=== OpenAI

* Identifier (`provider` argument): `"OpenAI"`
* https://platform.openai.com/docs/guides/embeddings[Official OpenAI documentation]

.Configuration map
[%header,cols="1m,1m,3a,2"]
|===
| Key | Type | Description | Default

| token
| STRING
| API access token.
| label:required[]

| model
| STRING
| The name of the model to invoke.
| `"text-embedding-ada-002"`

| dimensions
| INTEGER
| The number of dimensions to reduce the vector to. Only supported for certain models.
| Model-dependent.
|===


[[legacy-provider-vertex-ai]]
=== Vertex AI

* Identifier (`provider` argument): `"VertexAI"`
* https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings[Official Vertex AI documentation]

.Configuration map
[%header,cols="1m,1m,3a,2"]
|===
| Key | Type | Description | Default

| token
| STRING
| API access token.
| label:required[]

| projectId
| STRING
| GCP project ID.
| label:required[]

| model
| STRING
| The name of the model to invoke. +
| `"textembedding-gecko@001"`

| region
| STRING
| GCP region where to send the API requests. +
 +

.Supported values
[%collapsible]
====
* `"us-west1"`
* `"us-west2"`
* `"us-west3"`
* `"us-west4"`
* `"us-central1"`
* `"us-east1"`
* `"us-east4"`
* `"us-south1"`
* `"northamerica-northeast1"`
* `"northamerica-northeast2"`
* `"southamerica-east1"`
* `"southamerica-west1"`
* `"europe-west2"`
* `"europe-west1"`
* `"europe-west4"`
* `"europe-west6"`
* `"europe-west3"`
* `"europe-north1"`
* `"europe-central2"`
* `"europe-west8"`
* `"europe-west9"`
* `"europe-southwest1"`
* `"asia-south1"`
* `"asia-southeast1"`
* `"asia-southeast2"`
* `"asia-east2"`
* `"asia-east1"`
* `"asia-northeast1"`
* `"asia-northeast2"`
* `"australia-southeast1"`
* `"australia-southeast2"`
* `"asia-northeast3"`
* `"me-west1"`
====
| `"us-central1"`

| taskType
| STRING
| The intended downstream application (see link:https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings/[provider documentation]). The specified `taskType` will apply to all resources in a batch.
|

| title
| STRING
| The title of the document that is being encoded (see link:https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings/[provider documentation]). The specified `title` will apply to all resources in a batch.
|
|===


[[legacy-provider-azure-openai]]
=== Azure OpenAI

* Identifier (`provider` argument): `"AzureOpenAI"`
* https://learn.microsoft.com/en-us/azure/ai-foundry/[Official Azure OpenAI documentation]

[NOTE]
Unlike the other providers, the model is configured when creating the deployment on Azure, and is thus not part of the configuration map.

.Configuration map
[%header,cols="1m,1m,3a,2"]
|===
| Key | Type | Description | Default

| token
| STRING
| API access token.
| label:required[]

| resource
| STRING
| The name of the resource to which the model has been deployed.
| label:required[]

| deployment
| STRING
| The name of the model deployment.
| label:required[]

| dimensions
| INTEGER
| The number of dimensions to reduce the vector to. Only supported for certain models.
| Model-dependent.
|===


[[legacy-provider-amazon-bedrock]]
=== Amazon Bedrock

* Identifier (`provider` argument): `"Bedrock"`
* https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html[Official Bedrock documentation]

.Configuration map
[%header,cols="1m,1m,3a,2"]
|===
| Key | Type | Description | Default

| accessKeyId
| STRING
| AWS access key ID.
| label:required[]

| secretAccessKey
| STRING
| AWS secret key.
| label:required[]

| model
| STRING
| The name of the model to invoke. +
 +
Supported values: +
 +

* `"amazon.titan-embed-text-v1"`
| `"amazon.titan-embed-text-v1"`

| region
| STRING
| AWS region where to send the API requests. +
 +
Supported values: +
 +

* `"us-east-1"`
* `"us-west-2"`
* `"ap-southeast-1"`
* `"ap-northeast-1"`
* `"eu-central-1"`
| `"us-east-1"`

|===
