:description: Information about how the GenAI plugin can create, store, and query embeddings in external vector databases.
:page-role: new-2025.03

= Store and query embeddings on external vector databases

The GenAI plugin can store embeddings in an external vector database.
It can also be used to retrieve information about and query these externally hosted embeddings.
Doing this can offload your Neo4j instance from storing very large properties.

The GenAI plugin supports interacting with the following vector databases:

* link:https://docs.trychroma.com/[ChromaDB]
* link:https://milvus.io/docs[Milvus]
* link:https://docs.pinecone.io/guides[Pinecone]
* link:https://qdrant.tech/documentation/[Qdrant]
* link:https://weaviate.io/developers/weaviate[Weaviate]

[NOTE]
The examples on this page use *Qdrant* as the external vector database for storing, retrieving, and querying embeddings.


[#parameters]
== Preliminary parameters

All procedures to interact with external databases take a configuration map as last parameter, so it is convenient to store it in a parameter for usage in all procedure calls.
Parameters are set in different ways depending on the query tool you are using.

[source, cypher]
----
{
  "configuration": {
    "token": "<API token to external database>" // <.>
  }
}
----

<.> The API key to the external vector database.

Two other pieces of data that are often required in examples throughout the page are the external database collection name and an OpenAI token to generate embeddings, so we store those in parameters as well.

[source, cypher]
----
{
  "collection": "movies",  // <.>
  "openai_token": "<API token for OpenAI>" // <.>
}
----

<.> The collection name in the external vector database.
<.> An OpenAI token to generate vector embeddings (see xref:reference.adoc#ai-providers[GenAI providers] for supported alternatives to OpenAI). +
You can also avoid using cloud providers and rely on link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/embeddings/sentence-transformers/[open source alternatives].


[#manage-data]
== Create, update, and delete data in a collection

[#upsert-points]
.Generate and store embeddings in external database (small dataset)
====
To insert points into the vector database, use the procedure `genai.vector.external.upsert`.

[source, cypher]
----
MATCH (m:Movie) LIMIT 20
WITH collect(m) AS moviesList
WITH moviesList, [movie IN moviesList | movie.title || ': ' || movie.plot] AS batch
CALL genai.vector.encodeBatch(batch, 'OpenAI', { token: $openai_token }) YIELD index, vector  // <.>
WITH moviesList, index, vector
CALL genai.vector.external.upsert(  // <.>
    $qdrant_uri, // <.>
    $collection, // <.>
    [{  // <.>
        id: index,  // <.>
        vector: vector,
        metadata: {  // <.>
            title: moviesList[index]['title'],
            year: moviesList[index]['year']
        }
    }],
    $configuration  // <.>
) YIELD vendor
----

<.> The procedure `genai.vector.encodeBatch` generates embeddings for a list of strings.
For more information, see xref:neo4j-databases.adoc#multiple-embeddings[Generate a batch of embeddings and store them].
<.> The procedure `genai.vector.external.upsert` inserts (or updates, if the IDs exist already) points into the external vector database.
<.> The external database URI.
<.> The external database collection name.
<.> A list of points to insert into the external database, each containing an `id`, a `vector` embedding, and an optional `metadata` payload. +
<.> The allowed format of `id` depends on the external database provider -- in general, you should set identifiers that you can map back to Neo4j entities. For more information, see xref:id-mapping[Mapping entities between Neo4j and external databases]. +
<.> The metadata don't need to contain all the properties that the entity has in Neo4j. It is a good rule of thumb to include the Neo4j key property and any additional properties you may wish to xref:query[filter queries] on.
<.> A map containing (at minimum) the API token to the external database. For more information, see xref:parameters[Preliminary parameters].
====


[#upsert-points-large]
.Generate and store embeddings in external database (large dataset)
====

The previous example submits one request to the external database for each point to insert.
Although that is an easy way to get started, that workflow is guaranteed to be slow as the dataset size grows, and could result in throttling by the external provider.
A faster way is to submit batches of points to the external database.

[source, cypher]
----
MATCH (m:Movie)
WITH collect(m) AS moviesList,
    count(*) AS total,
    100 AS batchSize
UNWIND range(0, total-1, batchSize) AS batchStart
CALL (moviesList, batchStart, batchSize) {  // <.>
    WITH [movie IN moviesList[batchStart .. batchStart + batchSize] | movie.title || ': ' || movie.plot] AS batch
    CALL genai.vector.encodeBatch(batch, 'OpenAI', { token: $openai_token }) YIELD index, vector
    WITH collect({  // <.>
        id: index,
        vector: vector,
        metadata: {
            title: moviesList[batchStart + index]['title'],
            year: moviesList[batchStart + index]['year']
        }
    }) AS moviesWithEmbeddings
    CALL genai.vector.external.upsert(
        $qdrant_uri,
        $collection,
        moviesWithEmbeddings,
        $configuration
    ) YIELD vendor
    RETURN vendor
} IN CONCURRENT TRANSACTIONS OF 1 ROW
RETURN vendor
----

<.> `CALL` processes nodes in batches of size `batchSize`.
For more information on the structure of the example, see xref:neo4j-databases.adoc#encodebatch-large-dataset[Create embeddings from a large number of nodes and store them].
<.> The `collect` call creates a list of maps, each containing a point to insert.

[TIP]
This example may not scale to large datasets, as `collect(m)` requires the whole result set to be loaded in memory.
For an alternative method more suitable to processing large amounts of data, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/embeddings/cloud-providers/#_create_embeddings_for_movies[Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].
====


[#get-points]
.Retrieve points from external database
====
To verify that the insertion in external database was successful, you can retrieve a point's information via the procedure `genai.vector.external.get`.

[source, cypher]
----
CALL genai.vector.external.get( // <.>
    $qdrant_uri,  // <.>
    $collection, // <.>
    [1,2,3], // <.>
    $configuration // <.>
) YIELD id, metadata
RETURN id, metadata
----

<.> The procedure `genai.vector.external.get` retrieves points from the external vector database, given their IDs.
<.> The external database URI.
<.> The external database collection name.
<.> A list of IDs to retrieve from the external database.
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters]. +
By default, the procedure only retrieves the metadata for the given IDs.
If you want the `id` and `vector` fields populated as well, set `allResults: true` in the configuration map.
====

[#delete-points]
.Delete points from external database
====
To delete points from the external database, use the procedure `genai.vector.external.delete`.

[source, cypher]
----
CALL genai.vector.external.delete(  // <.>
    $qdrant_uri, // <.>
    $collection, // <.>
    [1,2,3], // <.>
    $configuration // <.>
) YIELD status, vendor
RETURN status, vendor
----

<.> The procedure `genai.vector.external.delete` removes points from the external vector database, given their IDs.
<.> The external database URI.
<.> The external database collection name.
<.> A list of IDs to delete from the external database.
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters].
====


[#query]
== Query a collection

Once the external database contains vector embeddings for the graph entities stored in your Neo4j database, you can use the `genai.vector.external.query` to retrieve points similar to an embedding for a given node.

.Query for similarity
[source, cypher]
----
MATCH (m:Movie {title: 'Toy Story'})
WITH m.title || ': ' || m.plot AS movieData
WITH genai.vector.encode(movieData, 'OpenAI', { token: $openai_token }) AS vector  // <.>
CALL genai.vector.external.query(  // <.>
    $qdrant_uri, // <.>
    $collection, // <.>
    vector, // <.>
    null, // <.>
    3, // <.>
    $configuration // <.>
) YIELD id, metadata, score
WHERE score < .999 // <.>
RETURN id, metadata, score
----

<.> The procedure `genai.vector.external.query` retrieves points similar to the provided `vector` from the external vector database.
<.> The external database URI.
<.> The external database collection name.
<.> The vector embedding that points should be compared to.
Results will be similar to this vector.
<.> A filter map (see next example).
<.> Number of similar points to return.
<.> Filter out the query vector (i.e. exclude `Toy Story` from return list).
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters].

The query returns the IDs of points close to the given vector.
To retrieve Neo4j entities corresponding to those IDs, you need to have set up your vector dataset in a way that allows you to map vectors to graph entities.
For more information, see xref:id-mapping[Mapping entities between Neo4j and external databases].

You can include a filter map to enforce some constraints on the query, depending on the points' metadata.

.Query for similarity, with constraints
[source, cypher]
----
MATCH (m:Movie {title: 'Toy Story'})
WITH m.title || ': ' || m.plot AS movieData
WITH genai.vector.encode(movieData, 'OpenAI', { token: $openai_token }) AS vector
CALL genai.vector.external.query(
    $qdrant_uri,
    $collection,
    vector,
    {  // <.>
      must: {
        key: 'year',
        match: {value: 1995}
      }
    },
    3,
    $configuration
) YIELD id, metadata, score
WHERE score < .999
RETURN id, metadata, score
----

<.> Restrict query space only to points for which the `year` metadata value is `1995`.
The structure and fields of this map depends on the external database provider (this example uses link:https://qdrant.tech/documentation/concepts/filtering/[Qdrant Filtering]).


[#id-mapping]
== Mapping entities between Neo4j and external databases

There needs to be a mapping between the graph entities in the Neo4j database and the points in the external vector database.
If your Neo4j dataset has a numerical or Universally Unique ID key property, you can use that to populate the IDs in the external database.
However, if you use a string property (such as movie titles) as key, you need to generate a deterministic 1:1 mapping so that you can map vector query results to Neo4j entities.
This is not possible through Cypher alone: you need to delegate this part of the workflow to your client application.

The example below shows how to use the link:https://neo4j.com/docs/python-manual/current/[Neo4j Python driver] to generate UUIDs from movie titles and upsert the corresponding points into Qdrant.

[source, python]
----
import neo4j
from uuid import uuid5


URI = '<URI for Neo4j database>'
AUTH = ('<Username>', '<Password>')
DB_NAME = '<Database name>'  # examples: 'recommendations-50', 'neo4j'
openai_token = '<OpenAI API token>'

namespace = 'neo4j-qdrant-movies'  # <.>

qdrant_uri = '<URI for Qdrant database>'
qdrant_collection = '<Name of Qdrant collection>'
qdrant_key = '<API key for Qdrant database>'
qdrant_config = { 'token': qdrant_key }

driver = neo4j.GraphDatabase.driver(URI, auth=AUTH)
driver.verify_connectivity()

with driver.session(database=DB_NAME) as session:
    result = session.run('''
        MATCH (m:Movie) LIMIT 5
        RETURN m.plot AS plot, m.title AS title
    ''')
    for record in result:
        title = record.get('title')
        plot = record.get('plot')
        qdrant_index = str(uuid5(namespace, title))  # <.>

        print(f'Processing movie `{title}`')
        session.run('''
            WITH genai.vector.encode(
                $title || ' ' || $plot,
                'OpenAI', { token: $token }
            ) AS vector
            CALL genai.vector.external.upsert($qdrant_uri, $collection, [{
              id: $index,
              vector: vector,
              metadata: {
                title: $title
              }
            }], $configuration) YIELD status, vendor
            RETURN status, vendor
        ''',
        title=title, plot=plot, index=qdrant_index, token=openai_token,
        qdrant_uri=qdrant_uri, collection=qdrant_collection, configuration=qdrant_config)
----

<.> The namespace is used as seed to generate deterministic UUIDs for movie titles.
You can change it to something different, but you need to use the same one throughout all `upsert` and `query` calls.
<.> Generate a UUID basing on the namespace seed and the movie title, to be used as point ID in the external database.


[query-get-andupdate]
== Query/Get points and update Neo4j entities

The procedures xref:get-points[`genai.vector.external.get`] and xref:query[`genai.vector.external.query`] retrieve vectors from the external database, either given a list of IDs or basing on a query embedding.

The procedures `genai.vector.external.getAndUpdate` and `genai.vector.external.queryAndUpdate` retrieve vectors in the same way, and they also update the corresponding Neo4j entities with data present in the external database.
It is a way to keep the two databases in sync: both metadata content and the embedding vector (if present) are updated in Neo4j, drawing from the external database.

The mapping between external vectors and graph entities is configured via a map entry under the key `mapping` in the configuration parameter.

[source, json]
----
{
  "mapping": {
    "nodeLabel": "<Neo4j label>",  // <.>
    "entityKey": "<Neo4j key property>",  // <.>
    "metadataKey": "<External key property>",  // <.>
    "embeddingKey": "<Neo4j vector property>"  // <.>
  }
}
----

<.> Label assigned to Neo4j nodes to be updated.
<.> Name of the property acting as node key in Neo4j.
<.> Name of the metadata entry in the external database matching the node key in Neo4j.
<.> (Optional) Name of the property containing the vector embedding in Neo4j.

[NOTE]
The entities must already exist in Neo4j: the procedures only _update_ existing nodes, but don't _create_ any new ones.

[#getandupdate]
.Retrieve points from external database and update corresponding Neo4j entities
====

[source, parameters]
----
{
  "configuration": {
    "token": "<API token to external database>"
  },
  "mapping": {
    "nodeLabel": "Movie",
    "entityKey": "title",
    "metadataKey": "title",
  }
}
----

[source, cypher]
----
CALL genai.vector.external.getAndUpdate( // <.>
    $qdrant_uri,  // <.>
    $collection, // <.>
    [1,2,3], // <.>
    $configuration // <.>
) YIELD id, metadata
RETURN id, metadata
----

<.> The procedure `genai.vector.external.getAndUpdate` retrieves points from the external vector database, given their IDs, and copies their information into the corresponding Neo4j entities.
<.> The external database URI.
<.> The external database collection name.
<.> A list of IDs from the external database.
<.> A map containing the API token to the external database and a mapping map.
====

[#queryandupdate]
.Query for similarity
====


[source, parameters]
----
{
  "configuration": {
    "token": "<API token to external database>"
  },
  "mapping": {
    "nodeLabel": "Movie",
    "entityKey": "title",
    "metadataKey": "title",
  }
}
----

[source, cypher]
----
MATCH (m:Movie {title: 'Toy Story'})
WITH m.title || ': ' || m.plot AS movieData
WITH genai.vector.encode(movieData, 'OpenAI', { token: $openai_token }) AS vector
CALL genai.vector.external.queryAndUpdate(  // <.>
    $qdrant_uri, // <.>
    $collection, // <.>
    vector, // <.>
    null, // <.>
    3, // <.>
    $configuration // <.>
) YIELD id, metadata, score
RETURN id, metadata, score
----

<.> The procedure `genai.vector.external.queryAndUpdate` retrieves points similar to the provided `vector` from the external vector database, and copies their information into the corresponding Neo4j entities.
<.> The external database URI.
<.> The external database collection name.
<.> The vector embedding that points should be compared to.
Results will be similar to this vector.
<.> A filter map (see next example).
<.> Number of similar points to return.
<.> A map containing the API token to the external database and a mapping map.

====


[#collection-management]
== Collection management

You can create and delete collections in the external vector database via Cypher procedures, as well retrieving information about existing collections.

.Create a new collection
====
[source, cypher]
----
CALL genai.vector.external.createCollection(
    $qdrant_uri, // <.>
    $collection, // <.>
    'Cosine', // <.>
    1536, // <.>
    $configuration // <.>
)
----

<.> The external database URI.
<.> The name of the new collection.
<.> The similarity function to be used for queries (valid values depend on the external database provider).
<.> The vector embeddings size.
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters].
====

.Retrieve information for a collection
====
[source, cypher]
----
CALL genai.vector.external.info(
    $qdrant_uri, // <.>
    $collection_name, // <.>
    $configuration // <.>
) YIELD *
----

<.> The external database URI.
<.> The name of the collection to retrieve information of.
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters].

.Example output for collection info
[source, output]
----
{
  "points_count": 0,
  "indexed_vectors_count": 0,
  "optimizer_status": "ok",
  "status": "green",
  "segments_count": 2,
  "config": {
    "quantization_config": null,
    "hnsw_config": {
    "max_indexing_threads": 0,
    "full_scan_threshold": 10000,
    "on_disk": false,
    "m": 16,
    "ef_construct": 100
    },
    "optimizer_config": {
    "indexing_threshold": 20000,
    "flush_interval_sec": 5,
    "default_segment_number": 0,
    "deleted_threshold": 0.2,
    "memmap_threshold": null,
    "max_segment_size": null,
    "vacuum_min_vector_number": 1000,
    "max_optimization_threads": null
    },
    "strict_mode_config": {
    "enabled": false
    },
    "params": {
    "vectors": {
        "distance": "Cosine",
        "size": 1536
    },
    "replication_factor": 1,
    "write_consistency_factor": 1,
    "on_disk_payload": true,
    "shard_number": 1
    },
    "wal_config": {
    "wal_segments_ahead": 0,
    "wal_capacity_mb": 32
    }
  },
  "payload_schema": {

  }
}
----
====

.Delete a collection
====
[source, cypher]
----
CALL genai.vector.external.deleteCollection(
    $qdrant_uri, // <.>
    $collection, // <.>
    $configuration // <.>
)
----

<.> The external database URI.
<.> The name of the collection to retrieve information of.
<.> A map containing (at minimum) the API token to the external database.
For more information, see xref:parameters[Preliminary parameters].
====


== Vector database provider details

