ifdef::backend-pdf[]
= Neo4j GenAI Plugin {page-version}
endif::[]
ifndef::backend-pdf[]
= Introduction
:description: Neo4j's GenAI plugin provides functions to interact with external AI providers through Cypher (create vector embeddings, generate text).
endif::[]

Neo4j's GenAI plugin provides functions and procedures to interact with external AI providers through Cypher, such as for creating vector embeddings and generating text.

[NOTE]
To use the plugin's features, you need an account and API credentials from one of the supported external AI providers: (OpenAI, Azure OpenAI, VertexAI, Amazon Bedrock).

[[installation]]
== Installation

**In link:https://neo4j.com/product/auradb/[Neo4j Aura]**, the GenAI plugin is enabled by default.

**On self-managed instances**, you install the plugin by moving the `neo4j-genai-plugin-<version>.jar` file from `<NEO4J_HOME>/products` to `<NEO4J_HOME>/plugins`, or, if you are using Docker, by starting the Docker container with the extra parameter `--env NEO4J_PLUGINS='["genai"]'`.
For more information, see link:{neo4j-docs-base-uri}/operations-manual/current/configuration/plugins/[Operations Manual -> Configure plugins].

[IMPORTANT]
Most GenAI features are available only in Cypher 25.
If your database's default language is Cypher 5, prepend the query with `CYPHER 25` to override the default for that query (see link:https://neo4j.com/docs/cypher-manual/current/queries/select-version/[Cypher -> Select Cypher version]).


[[setup]]
== Environment setup

The examples in this manual use the link:https://github.com/neo4j-graph-examples/recommendations[Neo4j movie recommendations] dataset, mostly focusing on the `plot` and `title` properties of `Movie` nodes.
There are 9083 `Movie` nodes with a `plot` and `title` property.

image::genai-graph.svg[Example graph connecting person and actor nodes with a movie node via acted in and directed relationships,width=600,role=popup]

To follow the examples in this manual, you need to import a dump file.
The file to import depends on the edition/deployment of Neo4j you are using and which link:{neo4j-docs-base-uri}/operations-manual/current/database-internals/store-formats/#store-format-overview[storage format] is available:

- Enterprise Edition or any Aura instance -- Import the link:https://github.com/neo4j-graph-examples/recommendations/raw/main/data/recommendations-5.26-block.dump[dump file] in block format.
- Community Edition -- Import the link:https://github.com/neo4j-graph-examples/recommendations/raw/main/data/recommendations-5.26.dump[dump file] in aligned format.

For instructions on importing dump files, see link:https://neo4j.com/docs/aura/managing-instances/backup-restore-export/#restore-backup[Aura -> Backup, export, restore, and upload] or link:https://neo4j.com/docs/operations-manual/current/backup-restore/restore-dump/[Operations manual -> Restore a database dump].
