:description: Information about Neo4j's GenAI plugin.
:page-role: new-5.17

= Introduction

Neo4j's GenAI plugin provides functions and procedures to interact with external AI providers through Cypher.

You can store and manipulate vector embeddings in Neo4j, but to interact with external AI providers (for example to create embeddings) you need an account and API credentials from one of the supported GenAI providers: xref:reference/ai-providers.adoc#vertex-ai[Vertex AI], xref:reference/ai-providers.adoc#openai[OpenAI], xref:reference/ai-providers.adoc#azure-openai[Azure OpenAI], and xref:reference/ai-providers.adoc#amazon-bedrock[Amazon Bedrock].


[[installation]]
== Installation

**In link:{neo4j-docs-base-uri}/aura/[Neo4j Aura]**, the GenAI plugin is enabled by default.

**On self-managed instances**, you install the plugin by moving the `neo4j-genai-plugin-<version>.jar` file from `<NEO4J_HOME>/products` to `<NEO4J_HOME>/plugins`, or, if you are using Docker, by starting the Docker container with the extra parameter `--env NEO4J_PLUGINS='["genai"]'`.
For more information, see link:{neo4j-docs-base-uri}/operations-manual/current/configuration/plugins/[Operations Manual -> Configure plugins].
