:description: Information about Neo4j's GenAI plugin.
:page-role: new-5.17

= Introduction

Neo4j's GenAI plugin can be used to integrate with various third party providers to perform AI tasks.

* Create vector embeddings based on text input.
* xref:text/completion/text-completion.adoc[Generate text].

To use the plugin you need an account and API credentials from any of the following GenAI providers: Vertex AI, OpenAI, Azure OpenAI, and Amazon Bedrock.

[[installation]]
== Installation

The GenAI plugin is enabled by default in link:{neo4j-docs-base-uri}/aura/[Neo4j Aura].

The plugin needs to be installed on self-managed instances.
This is done by moving the `neo4j-genai.jar` file from `/products` to `/plugins` in the Neo4j home directory, or, if you are using Docker, by starting the Docker container with the extra parameter `--env NEO4J_PLUGINS='["genai"]'`.
For more information, see link:{neo4j-docs-base-uri}/operations-manual/current/configuration/plugins/[Operations Manual -> Configure plugins].

[NOTE]
Prior to Neo4j 5.23, the GenAI plugin was only available on Neo4j Enterprise Edition.
