
= Create and store embeddings in a Neo4j database

Neo4j's link:{neo4j-docs-base-uri}/cypher-manual/current/indexes/semantic-indexes/vector-indexes[vector indexes] and link:{neo4j-docs-base-uri}/cypher-manual/functions/vector[vector functions] allow you to calculate the similarity between node and relationship properties in a graph.
A prerequisite for using these features is that vector embeddings have been set as properties of these entities.
This page shows how these embeddings can be created and stored as properties on nodes and relationships in a Neo4j database using the GenAI plugin.

[TIP]
For a hands-on guide on how to use the GenAI plugin on a Neo4j database, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/[Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].

[[example-graph]]
== Example graph

The examples on this page use the link:https://github.com/neo4j-graph-examples/recommendations[Neo4j movie recommendations] dataset, focusing on the `plot` and `title` properties of `Movie` nodes.

image::genai_graph.svg[width="600",role="middle"]

The graph contains 28863 nodes and 332522 relationships.
There are 9083 `Movie` nodes with a `plot` and `title` property.

To recreate the graph, download and import this link:https://github.com/neo4j-graph-examples/recommendations/blob/main/data/recommendations-embeddings-50.dump[dump file] to an empty Neo4j database (running version 5.17 or later).
Dump files can be imported for both link:{neo4j-docs-base-uri}/aura/auradb/importing/import-database/[Aura] and link:{neo4j-docs-base-uri}/operations-manual/current/backup-restore/restore-dump/[on-prem] instances.

[NOTE]
The embeddings on this are generated using link:https://platform.openai.com/docs/guides/embeddings[OpenAI] (model `text-embedding-ada-002`), producing 1536-dimensional vectors.

[[single-embedding]]
== Generate a single embedding and store it

Use the `genai.vector.encode()` function to generate a vector embedding for a single value.

.Signature for `genai.vector.encode()` label:function[]
[source,syntax]
----
genai.vector.encode(resource :: STRING, provider :: STRING, configuration :: MAP = {}) :: LIST<FLOAT>
----

* The `resource` (a `STRING`) is the object to transform into an embedding, such as a chunk text or a node/relationship property.
* The `provider` (a `STRING`) is the case-insensitive identifier of the provider to use.
See identifiers under xref:reference.adoc#ai-providers[] for supported options.
* The `configuration` (a `MAP`) contains provider-specific settings, such as which model to invoke, as well as any required API credentials.
See xref:reference.adoc#ai-providers[] for details of each supported provider.
Note that because this argument may contain sensitive data, it is obfuscated in the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/[query.log].
However, if the function call is misspelled or the query is otherwise malformed, it may be logged without being obfuscated.

[IMPORTANT]
====
This function sends one API request every time it is called, which may result in a lot of overhead in terms of both network traffic and latency.
If you want to generate many embeddings at once, use xref:neo4j-databases.adoc#multiple-embeddings[].
====

Use the `db.create.setNodeVectorProperty` procedure to store an embedding to a node property.

.Signature for `db.create.setNodeVectorProperty` label:procedure[]
[source,syntax]
----
db.create.setNodeVectorProperty(node :: NODE, key :: STRING, vector :: ANY)
----

Use the `db.create.setRelationshipVectorProperty` procedure to store an embedding to a relationship property.

.Signature for `db.create.setRelationshipVectorProperty` label:procedure[] label:new[Introduced in 5.18]
[source,syntax]
----
db.create.setRelationshipVectorProperty(relationship :: RELATIONSHIP, key :: STRING, vector :: ANY)
----

* `node` or `relationship` is the entity in which the new property will be stored.
* `key` (a `STRING`) is the name of the new property containing the embedding.
* `vector` is the object containing the embedding.

The embeddings are stored as properties on nodes or relationships with the type `LIST<INTEGER | FLOAT>`.

.Create an embedding from a single property and store it
====

.Create an embedding property for the Godfather
[source,cypher,role=test-skip]
----
MATCH (m:Movie {title:'Godfather, The'})
WHERE m.plot IS NOT NULL AND m.title IS NOT NULL
WITH m, m.title || ' ' || m.plot AS titleAndPlot // <1>
WITH m, genai.vector.encode(titleAndPlot, 'OpenAI', { token: $token }) AS propertyVector // <2>
CALL db.create.setNodeVectorProperty(m, 'embedding', propertyVector) // <3>
RETURN m.embedding AS embedding
----

<1> Concatenate the `title` and `plot` of the `Movie` into a single `STRING`.
<2> Create a 1536 dimensional embedding from the `titleAndPlot`.
<3> Store the `propertyVector` as a new `embedding` property on The Godfather node.

.Result
[source, "queryresult"]
----
+----------------------------------------------------------------------------------------------------+
| embedding                                                                                          |
+----------------------------------------------------------------------------------------------------+
| [0.005239539314061403, -0.039358530193567276, -0.0005175105179660022, -0.038706034421920776, ... ] |
+----------------------------------------------------------------------------------------------------+
----

[NOTE]
This result only shows the first 4 of the 1536 numbers in the embedding.
====

[[multiple-embeddings]]
== Generating a batch of embeddings and store them

Use the `genai.vector.encodeBatch` procedure to generate many vector embeddings with a single API request.
This procedure takes a list of resources as an input, and returns the same number of result rows, instead of a single one.

[IMPORTANT]
====
This procedure attempts to generate embeddings for all supplied resources in a single API request.
Therefore, it is recommended to see the respective provider's documentation for details on, for example, the maximum number of embeddings that can be generated per request.
====

.Signature for `genai.vector.encodeBatch` label:procedure[]
[source,syntax]
----
genai.vector.encodeBatch(resources :: LIST<STRING>, provider :: STRING, configuration :: MAP = {}) :: (index :: INTEGER, resource :: STRING, vector :: LIST<FLOAT>)
----

* The `resources` (a `LIST<STRING>`) parameter is the list of objects to transform into embeddings, such as chunks of text.
* The `provider` (a `STRING`) is the case-insensitive identifier of the provider to use.
See xref:reference.adoc#ai-providers[] for supported options.
* The `configuration` (a `MAP`) specifies provider-specific settings such as which model to invoke, as well as any required API credentials.
See xref:reference.adoc#ai-providers[] for details of each supported provider.
Note that because this argument may contain sensitive data, it is obfuscated in the link:https://neo4j.com/docs/operations-manual/current/monitoring/logging/[query.log].
However, if the function call is misspelled or the query is otherwise malformed, it may be logged without being obfuscated.

Each returned row contains the following columns:

* The `index` (an `INTEGER`) is the index of the corresponding element in the input list, to aid in correlating results back to inputs.
* The `resource` (a `STRING`) is the name of the input resource.
* The `vector` (a `LIST<FLOAT>`) is the generated vector embedding for this resource.

.Create embeddings from a limited number of properties and store them
====

[source, cypher, role=test-skip]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL)
WITH m
LIMIT 20
WITH collect(m) AS moviesList // <1>
WITH moviesList, [movie IN moviesList | movie.title || ': ' || movie.plot] AS batch // <2>
CALL genai.vector.encodeBatch(batch, 'OpenAI', { token: $token }) YIELD index, vector
WITH moviesList, index, vector
CALL db.create.setNodeVectorProperty(moviesList[index], 'embedding', vector) // <3>
----

<1> link:{neo4j-docs-base-uri}/cypher-manual/current/functions/aggregating/#functions-collect/[Collect] all  20 `Movie` nodes into a `LIST<NODE>`.
<2> Use a link:{neo4j-docs-base-uri}/cypher-manual/current/values-and-types/lists/#cypher-list-comprehension[list comprehension] (`[]`) to extract the `title` and `plot` properties of the movies in `moviesList` into a new `LIST<STRING>`.
<3> `db.create.setNodeVectorProperty` is run for each `vector` returned by `genai.vector.encodeBatch`, and stores that vector as a property named `embedding` on the corresponding node.
====

.Create embeddings from a large number of properties and store them
====
[source, cypher, role=test-skip]
----
MATCH (m:Movie WHERE m.plot IS NOT NULL)
WITH collect(m) AS moviesList, // <1>
     count(*) AS total,
     100 AS batchSize // <2>
UNWIND range(0, total-1, batchSize) AS batchStart // <3>
CALL (moviesList, batchStart, batchSize) { // <4>
    WITH [movie IN moviesList[batchStart .. batchStart + batchSize] | movie.title || ': ' || movie.plot] AS batch // <5>
    CALL genai.vector.encodeBatch(batch, 'OpenAI', { token: $token }) YIELD index, vector
    CALL db.create.setNodeVectorProperty(moviesList[batchStart + index], 'embedding', vector) // <6>
} IN CONCURRENT TRANSACTIONS OF 1 ROW <7>
----

<1> link:{neo4j-docs-base-uri}/cypher-manual/current/functions/aggregating/#functions-collect/[Collect] all returned `Movie` nodes into a `LIST<NODE>`.
<2> `batchSize` defines the number of nodes in `moviesList` to be processed at once.
Because vector embeddings can be very large, a larger batch size may require significantly more memory on the Neo4j server.
Too large a batch size may also exceed the provider's threshold.
<3> Process `Movie` nodes in increments of `batchSize`.
The end range `total-1` is due to `range` being inclusive on both ends.
<4> A link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions/[`CALL` subquery] executes a separate transaction for each batch.
Note that this `CALL` subquery uses a link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/call-subquery/#variable-scope-clause[variable scope clause] (introduced in Neo4j 5.23) to import variables.
If you are using an older version of Neo4j, use an link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/call-subquery/#importing-with[importing `WITH` clause] instead.
<5> `batch` is a list of strings, each being the concatenation of `title` and `plot` of one movie.
<6> The procedure sets `vector` as value for the property named `embedding` for the node at position `batchStart + index` in the `moviesList`.
<7> Set to `1` the amount of batches to be processed at once.
Concurrency in transactions was introduced in Cypher 5.21 (see link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transaction/#concurrent-transactions[`CALL` subqueries -> Concurrent transactions]).

[NOTE]
This example may not scale to larger datasets, as `collect(m)` requires the whole result set to be loaded in memory.
For an alternative method more suitable to processing large amounts of data, see link:https://neo4j.com/docs/genai/tutorials/embeddings-vector-indexes/[GenAI documentation - Embeddings & Vector Indexes Tutorial -> Create embeddings with cloud AI providers].

====
